---
title: "ATV:Trem2 vs Pathology DAM-like states"
author: "David Tatarakis"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
    toc_collapsed: true
---

```{r, include = FALSE}
Packages <-
  c(
    "dplyr",
    "Seurat",
    "aws.s3",
    "Matrix",
    "ggplot2",
    "pheatmap",
    "RColorBrewer",
    "scuttle",
    "SingleCellExperiment",
    "limma",
    "msigdbr",
    "fgsea",
    "sparrow",
    "edgeR"
  )
lapply(Packages, library, character.only = TRUE)

`%notin%` <- Negate(`%in%`)

set.seed(1234)

gg_color_hue <- function(n) {
  hues = seq(15, 375, length = n + 1)
  hcl(h = hues, l = 65, c = 100)[1:n]
}
```


# Combined Object
```{r}
combined <- readRDS("~/combined_object.Rds")

combined$mouse <- paste0(combined$group, "_", combined$sample_id)

# We will combine clusters 0 and 1 into 
# a single homeostatic cluster for simplicity
combined$clusters <- plyr::mapvalues(
  combined$seurat_clusters,
  from = c(0, 1, 2, 3, 4, 5),
  to = c(
    "Homeostatic",
    "Homeostatic",
    "cluster2",
    "cluster3",
    "cluster4",
    "cluster5"
  )
)
```

```{r}
DimPlot(combined, 
        group.by = "clusters", 
        cols = brewer.pal("Dark2", n = 6)[c(1, 3:6)])
```

```{r}
DefaultAssay(combined) <- "RNA"
sce2 <- as.SingleCellExperiment(combined)

meta2 <- transform(combined@meta.data)
## Pick the meta data we want to aggregate by
agg.df2 <- DataFrame(
  sample = meta2$sample_id,
  cluster = meta2$clusters,
  group = meta2$group
)

## Perform aggregation across these covariates and then build DGEList object

pbulk2 <-
  scuttle::aggregateAcrossCells(sce2, ids = agg.df2, use.altexps = F)
pbulk2$bulk_cell <-
  paste0(pbulk2$sample, "_", pbulk2$cluster, "_", pbulk2$group)
pbulk_dge2 <- edgeR::DGEList(
  counts = counts(pbulk2),
  samples = colData(pbulk2),
  group = colData(pbulk2)$cluster
)
```

```{r}
design <- model.matrix( ~ 0 + cluster + study,
                        data = pbulk_dge2$samples)
colnames(design) <- sub("^cluster", "", colnames(design))

fit <- voomLmFit(pbulk_dge2, design = design, plot = T)
contrasts <- makeContrasts(
  "2_vs_Hom" = "cluster2-Homeostatic",
  "3_vs_Hom" = "cluster3-Homeostatic",
  "4_vs_Hom" = "cluster4-Homeostatic",
  "5_vs_Hom" = "cluster5-Homeostatic",
  "4_vs_3" = "cluster4-cluster3",
  levels = design
)

fit2 <- contrasts.fit(fit, contrasts = contrasts)
fit2 <- eBayes(fit2, robust = FALSE)
```

```{r}
comps <- colnames(contrasts)

# Extract comparisons
toptables <- lapply(comps, function(x) {
  tt <- topTable(fit2, coef = x, number = Inf) %>%
    dplyr::mutate(Gene = rownames(.)) %>%
    dplyr::mutate(FDR = adj.P.Val) %>%
    dplyr::mutate(feature_id = Gene)
  rownames(tt) <- tt$feature_id
  tt
})

names(toptables) <- comps
```

```{r}
genes_to_plot <-
  c(
    "Apoe",
    "Cst7",
    "Lpl",
    "Ccl4",
    "Top2a",
    "Mki67",
    "Ifitm3",
    "Isg15",
    "Gpnmb",
    "Spp1",
    "Mif",
    "Ldha",
    "Cox5a"
  )
```

```{r}
simpleVolcano(
  DE = toptables$`2_vs_Hom`,
  fcColumn = "logFC",
  pColumn = "adj.P.Val",
  geneCol = "Gene",
  labels = genes_to_plot
) +
  ggtitle("Cluster2 vs Homeostatic")
```

```{r}
simpleVolcano(
  DE = toptables$`3_vs_Hom`,
  fcColumn = "logFC",
  pColumn = "adj.P.Val",
  geneCol = "Gene",
  labels = genes_to_plot
) +
  ggtitle("Cluster3 vs Homeostatic")
```

```{r}
simpleVolcano(
  DE = toptables$`4_vs_Hom`,
  fcColumn = "logFC",
  pColumn = "adj.P.Val",
  geneCol = "Gene",
  labels = genes_to_plot
) +
  ggtitle("Cluster4 vs Homeostatic")
```

```{r}
simpleVolcano(
  DE = toptables$`5_vs_Hom`,
  fcColumn = "logFC",
  pColumn = "adj.P.Val",
  geneCol = "Gene",
  labels = genes_to_plot
) +
  ggtitle("Cluster5 vs Homeostatic")
```

```{r}
simpleVolcano(
  DE = toptables$`4_vs_3`,
  fcColumn = "logFC",
  pColumn = "adj.P.Val",
  geneCol = "Gene",
  labels = genes_to_plot
) +
  ggtitle("Cluster4 vs Cluster3")
```

```{r}
toptables_df <- purrr::map_df(comps, function(x) {
  tt <- topTable(fit2, coef = x, number = Inf) %>%
    dplyr::mutate(Gene = rownames(.)) %>%
    dplyr::mutate(FDR = adj.P.Val) %>%
    dplyr::mutate(feature_id = Gene)
  rownames(tt) <- tt$feature_id
  tt %>% mutate(comp = x)
})

logFC_df <- toptables_df %>%
  dplyr::filter(comp != "4_vs_3") %>%
  group_by(Gene) %>%
  dplyr::mutate(pval.min = min(adj.P.Val)) %>%
  dplyr::filter(pval.min <= 0.01)  %>%
  dplyr::select(c(Gene, logFC, comp)) %>%
  tidyr::pivot_wider(names_from = comp, values_from = logFC) %>%
  dplyr::ungroup()

logFC_mat <- as.matrix(logFC_df %>% dplyr::select(-Gene))
rownames(logFC_mat) <- logFC_df$Gene

chen_sigs <- read.csv("/inst/extdata/state_signatures.csv") %>%
  dplyr::filter(collection == "ChenColonna2021") %>%
  dplyr::filter(symbol %in% logFC_df$Gene)


# Make a data frame binarizing the signifcance for each gene in each comparison

sig_df <- toptables_df %>%
  dplyr::filter(comp != "4_vs_3") %>%
  dplyr::select(c(Gene, adj.P.Val, comp)) %>%
  tidyr::pivot_wider(names_from = comp, values_from = adj.P.Val)

sig_df[,-1] <- ifelse(sig_df <= 0.05, 1, 0)[, -1]
```

```{r}
cols <-
  rev(colorRampPalette(RColorBrewer::brewer.pal(11, "RdBu"))(256))
cols <- colorRampPalette(c("blue3", "White", "red3"))(256)

breaks <- c(seq(min(logFC_mat), 0, length.out = ceiling(256 / 2)),
            seq(max(logFC_mat) / 256, max(logFC_mat), length.out = floor(256 /
                                                                           2)))


heatmap_genes <-
  c(chen_sigs$symbol, "Aldoa", "Gapdh", "Mif", "Cox5a", "Ldha")
toPlot <- logFC_mat[heatmap_genes, ]

sig_df <-
  sig_df %>% dplyr::filter(Gene %in% heatmap_genes) %>% as.data.frame()
rownames(sig_df) <- sig_df$Gene
sig_df <- sig_df %>% select(-Gene)

sig_df$`2_vs_Hom` <- as.character(sig_df$`2_vs_Hom`)
sig_df$`3_vs_Hom` <- as.character(sig_df$`3_vs_Hom`)
sig_df$`4_vs_Hom` <- as.character(sig_df$`4_vs_Hom`)
sig_df$`5_vs_Hom` <- as.character(sig_df$`5_vs_Hom`)

sig_colors <- list(
  `2_vs_Hom` = c(`0` = "White", `1` = "gray40"),
  `3_vs_Hom` = c(`0` = "White", `1` = "gray40"),
  `4_vs_Hom` = c(`0` = "White", `1` = "gray40"),
  `5_vs_Hom` = c(`0` = "White", `1` = "gray40")
)


logFC_df <-
  logFC_df %>% group_by(Gene) %>% 
  dplyr::mutate(avg_2_4 = mean(c(`2_vs_Hom`, `2_vs_Hom`)))

logFC_df <-
  logFC_df %>% 
  dplyr::mutate(label = ifelse(Gene %in% genes_to_plot, "yes", "no"))
```

```{r, fig.width=4.5, fig.height=8.5}
pheatmap::pheatmap(
  mat = toPlot[c(1:5, 16:40, 50:55, 56:nrow(toPlot), 41:45), ],
  scale = "none",
  cluster_cols = F,
  cluster_rows = F,
  show_rownames = T,
  show_colnames = T,
  annotation_row = rev(sig_df),
  annotation_colors = sig_colors,
  breaks = breaks,
  gaps_row = c(5, 30, 36, 41, 46),
  main = "Chen/Colonna Review Signature Genes",
  color = cols
)
```

```{r}
gdb <- getMSigGeneSetDb(c("h"), "mouse", id.type = "symbol")


gsea_df <- purrr::map_df(toptables, function(tt) {
  sparrow_h <-
    sparrow::seas(
      x = tt,
      gsd = gdb,
      methods = "fgsea",
      rank_by = "t"
    )
  gsea.h.res <- as.data.frame(result(sparrow_h, 'fgsea'))
  
}, .id = "comp")
```


```{r}
gsea_df <-
  gsea_df %>% dplyr::filter(
    name %in% c(
      "HALLMARK_G2M_CHECKPOINT",
      "HALLMARK_MYC_TARGETS_V1",
      "HALLMARK_GLYCOLYSIS",
      "HALLMARK_FATTY_ACID_METABOLISM",
      "HALLMARK_OXIDATIVE_PHOSPHORYLATION",
      "HALLMARK_CHOLESTEROL_HOMEOSTASIS",
      "HALLMARK_ALLOGRAFT_REJECTION",
      "HALLMARK_INTERFERON_ALPHA_RESPONSE",
      "HALLMARK_INTERFERON_GAMMA_RESPONSE",
      "HALLMARK_TNFA_SIGNALING_VIA_NFKB"
    )
  )

gsea_df$name <- sub("HALLMARK_", "", gsea_df$name)
gsea_df$name <- sub("_", " ", gsea_df$name)
gsea_df$name <- sub("_", " ", gsea_df$name)

gsea_df <- gsea_df %>% dplyr::filter(comp != "4_vs_3")
gsea_df <-
  gsea_df %>% dplyr::mutate(direction = ifelse(NES >= 0, "up", "down"))
```

```{r, fig.width=3, fig.height=3}
ggplot(gsea_df, aes(
  x = comp,
  y = name,
  color = direction,
  size = -log10(padj)
)) +
  geom_point() +
  scale_color_manual(values = c("blue2", "red2")) +
  theme_bw()
```

```{r, fig.width=2.5, fig.height=2.5}
ggplot(logFC_df,
       aes(
         x = `3_vs_Hom`,
         y = `2_vs_Hom`,
         color = label,
         size = label
       )) +
  geom_point() +
  theme_bw() +
  ylim(c(-2.5, 6.25)) +
  xlim(c(-2.5, 6.25)) +
  scale_size_manual(values = c(0.1, 2)) +
  scale_color_manual(values = c("gray80", "Orange2")) +
  geom_hline(yintercept = 0) +
  geom_vline(xintercept = 0) +
  geom_abline(slope = 1, linetype = "dashed") +
  ggrepel::geom_label_repel(
    label = ifelse(logFC_df$label == "yes",
                   logFC_df$Gene,
                   NA),
    box.padding = unit(0.25, "lines"),
    hjust = 0.25,
    max.overlaps = 100
  ) +
  theme(legend.position = "none")
```

```{r, fig.width=2.5, fig.height=2.5}
ggplot(logFC_df,
       aes(
         x = `3_vs_Hom`,
         y = `5_vs_Hom`,
         color = label,
         size = label
       )) +
  geom_point() +
  theme_bw() +
  ylim(c(-2.5, 6.25)) +
  xlim(c(-2.5, 6.25)) +
  scale_size_manual(values = c(0.1, 2)) +
  scale_color_manual(values = c("gray80", "Orange2")) +
  geom_hline(yintercept = 0) +
  geom_vline(xintercept = 0) +
  geom_abline(slope = 1, linetype = "dashed") +
  ggrepel::geom_label_repel(
    label = ifelse(logFC_df$label == "yes",
                   logFC_df$Gene,
                   NA),
    box.padding = unit(0.5, "lines"),
    hjust = 0.25,
    max.overlaps = 100
  ) +
  theme(legend.position = "none")
```
